# Data preprocessing for field validation

In [1]:
import sys
import pandas as pd  
import matplotlib.pyplot as plt
sys.path.append('../../')   # Add parent directory to Python path
from utils.visualization import *

## data label

In [2]:
# read the label CSV file
df_label = pd.read_csv('../../data/field_validation/labels.csv')
df_label

    Unnamed: 0                      NTP  Label
0            0  2025-10-21 15:20:07.944      1
1            1  2025-10-21 15:20:08.941      0
2            2  2025-10-21 15:20:12.937      5
3            3  2025-10-21 15:20:13.944      0
4            4  2025-10-21 15:20:20.940      1
..         ...                      ...    ...
89          89  2025-10-21 15:54:45.942      0
90          90  2025-10-21 15:54:51.941      5
91          91  2025-10-21 15:54:52.937      0
92          92  2025-10-21 15:55:56.939      1
93          93  2025-10-21 15:55:57.945      0

[94 rows x 3 columns]

In [ ]:
# Reset index to make the old index a column, then set Timestamp as new index
df_label = df_label.rename(columns={'NTP': 'Timestamp'})
df_label = df_label.set_index('Timestamp')

In [7]:
df_label.drop(columns=['Unnamed: 0'], inplace=True)

In [9]:
df_label.to_csv('../../data/field_validation/data_labels_accelerometer.csv', index=True)
df_label.head()

                         Label
Timestamp
2025-10-21 15:20:07.944      1
2025-10-21 15:20:08.941      0
2025-10-21 15:20:12.937      5
2025-10-21 15:20:13.944      0
2025-10-21 15:20:20.940      1

## data accelerometer

In [9]:
df_accelerometer = pd.read_csv('../../../data/field_validation/data_accelerometer.csv')

In [10]:
df_accelerometer

,Date,NTP,GNSS-Time,Acc-X,Acc-Y,Acc-Z
0,2025-10-21T15:15:40.982,2025-10-21 15:15:40.355,-1,-1.877060,6.095642,5.679047
1,2025-10-21T15:15:40.986,2025-10-21 15:15:40.360,-1,0.110138,6.258438,6.655884
2,2025-10-21T15:15:40.991,2025-10-21 15:15:40.365,-1,2.231400,6.584061,7.422028
3,2025-10-21T15:15:41,2025-10-21 15:15:40.374,-1,3.045425,6.833054,7.599197
4,2025-10-21T15:15:41.002,2025-10-21 15:15:40.375,-1,2.686295,6.823471,7.129929
...,...,...,...,...,...,...
494132,2025-10-21T15:56:52.485,2025-10-21 15:56:51.859,1761055011988,-0.196320,5.956772,8.523361
494133,2025-10-21T15:56:52.491,2025-10-21 15:56:51.865,1761055011994,-0.004791,5.990295,8.475479
494134,2025-10-21T15:56:52.494,2025-10-21 15:56:51.868,1761055011997,0.095764,6.019028,8.384491
494135,2025-10-21T15:56:52.500,2025-10-21 15:56:51.874,1761055012003,-0.148438,5.702988,8.341400
494136,2025-10-21T15:56:52.503,2025-10-21 15:56:51.877,1761055012006,-0.220261,5.339066,8.389282

In [11]:
# Rename NTP to Timestamp and set as index
df_accelerometer = df_accelerometer.rename(columns={'NTP': 'Timestamp'})
df_accelerometer = df_accelerometer.set_index('Timestamp')
df_accelerometer.head()

,Date,GNSS-Time,Acc-X,Acc-Y,Acc-Z
Timestamp,,,,,
2025-10-21 15:15:40.355,2025-10-21T15:15:40.982,-1,-1.877060,6.095642,5.679047
2025-10-21 15:15:40.360,2025-10-21T15:15:40.986,-1,0.110138,6.258438,6.655884
2025-10-21 15:15:40.365,2025-10-21T15:15:40.991,-1,2.231400,6.584061,7.422028
2025-10-21 15:15:40.374,2025-10-21T15:15:41,-1,3.045425,6.833054,7.599197
2025-10-21 15:15:40.375,2025-10-21T15:15:41.002,-1,2.686295,6.823471,7.129929

In [12]:
df_accelerometer.to_csv('../../../data/field_validation/data_accelerometer_cleaned.csv')