# Data Visualization for Road Roughness

In [1]:
import sys
import pandas as pd  
import matplotlib.pyplot as plt
sys.path.append('../../')   # Add parent directory to Python path
from utils.visualization import *

In [3]:
def label_curb_scenes(df_data, df_curb, milliseconds=500, save_path=None):
    """
    Labels curb scenes in the data and extends labels to surrounding data points for validation test.
    
    Args:
        df_data (pd.DataFrame): Original dataframe containing NTP and Acc-Z data
        df_curb (pd.DataFrame): Dataframe containing curb timestamps
        milliseconds (int): Time threshold in milliseconds
        save_path (str, optional): Path to save the CSV file. If None, file won't be saved
        
    Returns:
        pd.DataFrame: DataFrame with labeled curb scenes
    """
    # Create copy with selected columns
    df_selected = df_data[['NTP', 'Acc-X', 'Acc-Y', 'Acc-Z']].copy()
    df_selected['label'] = 0
    
    # Convert NTP columns to datetime
    df_selected['NTP'] = pd.to_datetime(df_selected['NTP'])
    df_curb['NTP'] = pd.to_datetime(df_curb['NTP'])
    
    # Only get timestamps where Label is not 0, 8, or 9
    curb_timestamps = df_curb[~df_curb['Label'].isin([0, 8, 9])]['NTP'].tolist()
    print(f"Number of curb scenes to label: {len(curb_timestamps)}")

    # Use a time threshold approach
    time_threshold = pd.Timedelta(milliseconds=milliseconds)
    for curb_time in curb_timestamps:
        mask = abs(df_selected['NTP'] - curb_time) <= time_threshold
        df_selected.loc[mask, 'label'] = 1
    
    # Save to CSV if path is provided
    if save_path:
        df_selected.to_csv(save_path, index=False)

    return df_selected

Road Roughness Data:<br>
a. AB - 08.07<br>
b. IK - 26.02.25<br>
c. JG - 03.07<br>
d. KF - 04.07<br>
e. LB - 18.06<br>
f. LCL - 03.07

## AB - 08.07

In [6]:
df_AB_label= pd.read_csv('../../data/Real_world_cycling/AB - 08.07/iphone_labels_annotation_cls5_tuned_cls9.csv')
df_AB_label

    Unnamed: 0                Timestamp  Label
0            0  2024-07-08 13:50:43.455      0
1            1  2024-07-08 13:53:37.806      1
2            2  2024-07-08 13:53:38.774      0
3            3  2024-07-08 13:53:42.927      5
4            4  2024-07-08 13:53:43.807      0
..         ...                      ...    ...
60          60  2024-07-08 14:16:28.632      0
61          61  2024-07-08 14:16:57.945      4
62          62  2024-07-08 14:16:59.131      0
63          63  2024-07-08 14:17:16.723      5
64          64  2024-07-08 14:17:17.483      0

[65 rows x 3 columns]

In [7]:
df_AB= pd.read_csv('../../data/Real_world_cycling/AB - 08.07/Lenker/Accelerometer/Accelerometer.0.csv')  
df_AB

,Date,NTP,GNSS-Time,Acc-X,Acc-Y,Acc-Z
0,2024-07-08T13:47:56.260,2024-07-08 13:47:58.136,-1,-0.220276,6.418854,7.252045
1,2024-07-08T13:47:56.282,2024-07-08 13:47:58.156,-1,-0.254990,6.369782,7.377731
2,2024-07-08T13:47:56.296,2024-07-08 13:47:58.171,-1,-0.146042,6.463150,7.224503
3,2024-07-08T13:47:56.316,2024-07-08 13:47:58.191,-1,-0.280121,6.424850,7.234085
4,2024-07-08T13:47:56.337,2024-07-08 13:47:58.211,-1,-0.217880,6.441605,7.236481
...,...,...,...,...,...,...
63107,2024-07-08T14:19:16.543,2024-07-08 14:19:18.417,1720441158385,1.769318,6.313507,7.186600
63108,2024-07-08T14:19:16.572,2024-07-08 14:19:18.447,1720441158415,1.798050,6.293564,7.194580
63109,2024-07-08T14:19:16.604,2024-07-08 14:19:18.478,1720441158446,1.771713,6.285584,7.202560
63110,2024-07-08T14:19:16.632,2024-07-08 14:19:18.507,1720441158474,1.801239,6.282379,7.237671
63111,2024-07-08T14:19:16.662,2024-07-08 14:19:18.537,1720441158504,1.782883,6.255249,7.249649

In [ ]:
df_AB_label_old= pd.read_csv('../../data/Real_world_cycling/AB - 08.07/data_labels_1gt.csv')  
df_AB_label_old

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,NTP,Timestamp,Video,Latitude,Longitude,Altitude,Speed,Label
0,0,0,0,"2024-07-08, 13:50:43.4400","2024-07-08, 13:50:43.4100",00:00.2,51.311692,9.474107,169.580547,-1.000000,0
1,1,1,1,"2024-07-08, 13:50:43.4400","2024-07-08, 13:50:43.4100",00:00.2,51.311692,9.474107,169.580547,-1.000000,0
2,2,2,2,"2024-07-08, 13:50:45.8280","2024-07-08, 13:50:45.7980",00:02.6,51.311834,9.474116,169.550388,-1.000000,0
3,3,3,3,"2024-07-08, 13:50:47.1110","2024-07-08, 13:50:47.0810",00:03.9,51.311830,9.474127,169.525043,-1.000000,0
4,4,4,4,"2024-07-08, 13:50:48.7460","2024-07-08, 13:50:48.7160",00:05.5,51.311621,9.473992,155.154792,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...
1702,1702,1702,1702,"2024-07-08, 14:19:07.1370","2024-07-08, 14:19:07.1070",28:23.9,51.311322,9.473877,172.446683,0.003840,0
1703,1703,1703,1703,"2024-07-08, 14:19:08.1370","2024-07-08, 14:19:08.1070",28:24.9,51.311321,9.473877,172.439117,0.021946,0
1704,1704,1704,1704,"2024-07-08, 14:19:09.1370","2024-07-08, 14:19:09.1070",28:25.9,51.311321,9.473877,172.442501,0.000000,0
1705,1705,1705,1705,"2024-07-08, 14:19:10.1370","2024-07-08, 14:19:10.1070",28:26.9,51.311321,9.473877,172.442501,0.000000,0
1706,1706,1706,1706,"2024-07-08, 14:19:11.1370","2024-07-08, 14:19:11.1070",28:27.9,51.311321,9.473877,172.442501,0.000000,0

In [10]:
df_AB_label_old['Label'].value_counts()

Label
0    1681
3      18
1       8
Name: count, dtype: int64

In [4]:
df_AB= pd.read_csv('../../data/Real_world_cycling/AB - 08.07/Lenker/Accelerometer/Accelerometer.0.csv')  
df_AB_label= pd.read_csv('../../data/Real_world_cycling/AB - 08.07/iphone_labels_annotation_cls5_tuned_cls9.csv')
df_AB_label['Label'].value_counts()

Label
0    32
4     9
1     8
5     6
8     3
6     2
7     2
3     1
2     1
9     1
Name: count, dtype: int64

In [5]:
df_AB_labeled = label_curb_scenes(df_AB, df_AB_label, milliseconds=500)

KeyError: 'NTP'

## IK - 26.02.25

In [27]:
df_IK= pd.read_csv('../../data/Real_world_cycling/IK - 26.02.25/Lenker/Accelerometer/Accelerometer.0.csv')  
df_IK_label= pd.read_csv('../../data/Real_world_cycling/IK - 26.02.25/data_labels_1gt.csv')
df_IK_label['Label'].value_counts()
df_IK_labeled = label_curb_scenes(df_IK, df_IK_label, milliseconds=500, save_path='../../data/Real_world_cycling/IK - 26.02.25/Accelerometer_labeled.csv')

Label
0    1626
3      21
1      16
Name: count, dtype: int64

## JG - 03.07

In [11]:
df_JG_label = pd.read_csv('../../data/Real_world_cycling/JG - 03.07/data_labels_1gt.csv')
df_JG_label

,Unnamed: 0,NTP,Timestamp,Video,Latitude,Longitude,Altitude,Speed,Label
0,0,"2024-07-03, 14:14:20.7900","2024-07-03, 14:14:20.7560",00:00.2,51.311383,9.474083,169.447723,-1.000000,0
1,1,"2024-07-03, 14:14:20.7910","2024-07-03, 14:14:20.7570",00:00.2,51.311383,9.474083,169.447723,-1.000000,0
2,2,"2024-07-03, 14:14:22.0010","2024-07-03, 14:14:21.9670",00:01.4,51.311353,9.473917,169.447723,-1.000000,0
3,3,"2024-07-03, 14:14:25.1180","2024-07-03, 14:14:25.0840",00:04.5,51.311546,9.473834,168.971963,0.000000,0
4,4,"2024-07-03, 14:14:26.1010","2024-07-03, 14:14:26.0680",00:05.5,51.311546,9.473834,168.971963,0.000000,0
...,...,...,...,...,...,...,...,...,...
1545,1545,"2024-07-03, 14:40:07.1280","2024-07-03, 14:40:07.0950",25:46.5,51.311362,9.473878,171.943501,1.975742,0
1546,1546,"2024-07-03, 14:40:08.1300","2024-07-03, 14:40:08.0960",25:47.5,51.311350,9.473878,172.171941,1.574669,0
1547,1547,"2024-07-03, 14:40:09.1450","2024-07-03, 14:40:09.1110",25:48.5,51.311319,9.473877,171.094037,0.576553,0
1548,1548,"2024-07-03, 14:40:10.1300","2024-07-03, 14:40:10.0960",25:49.5,51.311320,9.473877,171.882426,0.070600,0
1549,1549,"2024-07-03, 14:40:11.1280","2024-07-03, 14:40:11.0950",25:50.5,51.311313,9.473877,172.503756,0.090215,0

In [32]:
df_JG = pd.read_csv('../../data/Real_world_cycling/JG - 03.07/Lenker/Accelerometer/Accelerometer.0.csv')
df_JG_label = pd.read_csv('../../data/Real_world_cycling/JG - 03.07/data_labels_1gt.csv')
print(df_JG_label['Label'].value_counts())
df_JG_labeled = label_curb_scenes(df_JG, df_JG_label, milliseconds=500, save_path='../../data/Real_world_cycling/JG - 03.07/Accelerometer_labeled.csv')

Label
0    1545
1       3
3       2
Name: count, dtype: int64
Number of curb scenes to label: 5

## KF - 04.07

In [33]:
df_KF = pd.read_csv('../../data/Real_world_cycling/KF - 04.07/Lenker/Accelerometer/Accelerometer.0.csv')
df_KF_label = pd.read_csv('../../data/Real_world_cycling/KF - 04.07/data_labels_1gt.csv')
print(df_KF_label['Label'].value_counts())
df_KF_labeled = label_curb_scenes(df_KF, df_KF_label, milliseconds=500, save_path='../../data/Real_world_cycling/KF - 04.07/Accelerometer_labeled.csv')

Label
0    1489
1       3
3       2
Name: count, dtype: int64
Number of curb scenes to label: 5

## LB - 18.06

In [38]:
df_LB = pd.read_csv('../../data/Real_world_cycling/LB - 18.06/Lenker/Accelerometer/Accelerometer.0.csv')
df_LB_label = pd.read_csv('../../data/Real_world_cycling/LB - 18.06/data_labels_1gt.csv')
print(df_LB_label['Label'].value_counts())
df_LB_labeled = label_curb_scenes(df_LB, df_LB_label, milliseconds=500, save_path='../../data/Real_world_cycling/LB - 18.06/Accelerometer_labeled.csv')

Label
0    1321
2      28
4       1
1       1
3       1
Name: count, dtype: int64
Number of curb scenes to label: 31

## LCL - 03.07

In [39]:
df_LCL = pd.read_csv('../../data/Real_world_cycling/LCL - 03.07/Lenker/Accelerometer/Accelerometer.0.csv')
df_LCL_label = pd.read_csv('../../data/Real_world_cycling/LCL - 03.07/data_labels_1gt.csv')
print(df_LCL_label['Label'].value_counts())
df_LCL_labeled = label_curb_scenes(df_LCL, df_LCL_label, milliseconds=500, save_path='../../data/Real_world_cycling/LCL - 03.07/Accelerometer_labeled.csv')

Label distribution in LCL dataset:
Label
0    1590
1      15
3      12
Name: count, dtype: int64
Number of curb scenes to label: 27